apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sandbox
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sandbox
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: 3111
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: 3111
{{ toYaml .Values.resources | indent 8 }}
status: { }